FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade --yes
RUN apt-get install unminimize --yes
RUN yes | unminimize
RUN apt-get install man --yes
RUN apt-get install --yes \
   curl \
   git \
   xz-utils \
   make \
   nodejs \
   npm \
   guile-3.0 \
   guile-gnutls \
   guile-fibers
ENV DEBIAN_FRONTEND=

RUN npm install -g @fission-ai/openspec@latest

RUN npm install -g @mariozechner/pi-coding-agent

RUN npm install -g opencode-ai

WORKDIR /usr/local
RUN curl --location --silent "https://github.com/npryce/adr-tools/archive/refs/tags/3.0.0.tar.gz" | tar -xz
ENV PATH="/usr/local/adr-tools-3.0.0/src:${PATH}"
